build:
  cuda_version: "12.1.1"
  python_packages:
    - "requests==2.31.0"
    - "transformers"
    - "torch==2.1.1"
    - "sentencepiece==0.1.99"
    - "librosa==0.10.1"
    - "noisereduce==3.0.0"
    - "numpy==1.26.1"
    - "soundfile==0.12.1"
    - "huggingface-hub==0.25.2"
